apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-example
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cron-example
              image: kubes-example
              imagePullPolicy: Never
              command: ["cron"]
          restartPolicy: Never
