# TODO read more into ingress controllers
# TODO: can we not translate 80 -> 8000 over ingress or service?
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-api-ingress
spec:
  ingressClassName: {{ .Release.Name }}-api-ingress
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-api-service
                port:
                  number: {{ .Values.portVals.port }}
